# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
react:
  title: Memoizable
  name: Hariharan Viswanathan
  menu_right_subtitle: Polyglot coder | Distributed architecture enthusiast
  avatar: https://avatars2.githubusercontent.com/u/7565404?s=400&u=cf5879915d2919967214e740195e1d7196fe0682&v=4
  logo: static/img/memoize/memoize.png
  email: hariharanv01@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
    An avid Coder with 10 plus years' experience in product and system development. Designed and developed highly scalable, distributed and performant large-scale systems that handle millions of requests every day
  baseurl: "" # the subpath of your site, e.g. /blog
  ourl: "http://memoizable.com" # the base hostname & protocol for your site
  url: "http://memoizable.com"
  permalink: /posts/:title
  social:
    github: http://github.com/hariharanv01
    linkedin: https://www.linkedin.com/in/hariharanviswanathan/
    rss: http://memoizable.com/feed.xml
  detach:  false
  port:    80
  # host:    memoizable.com
  show_dir_listing: false

detach:  false
port:    80
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

title: Memoizable
name: Hariharan Viswanathan
menu_right_subtitle: Coder
avatar: https://avatars2.githubusercontent.com/u/7565404?s=400&u=cf5879915d2919967214e740195e1d7196fe0682&v=4
logo: static/img/memoize/res/mipmap-xhdpi/memoize.png
email: hariharanv01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An avid Coder with 10 plus years' experience in product and system development. Designed and developed highly scalable, distributed and performant large-scale systems that handle millions of requests every day
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://memoizable.com" # the base hostname & protocol for your site
permalink: /posts/:title

github_username: hariharanv01


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: public

assets:
  compress:
    css: sass
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: www.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh']

plugins_dir:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react
